### ISSUE TITLE
Cannot read property 'ctime' of null

### ISSUE THREAD

**Issue by AlexanderKozhevin** [shonny-ua/gulp-rev-outdated#9]
Sometimes I'm getting some this error message. Does it try to read not existing file?

```
/Users/alexanderkozhevin/Documents/eaglefront/node_modules/gulp-rev-outdated/index.js:23
                time: file.stat.ctime.getTime()
                               ^

TypeError: Cannot read property 'ctime' of null
  at DestroyableTransform._transform (/Users/alexanderkozhevin/Documents/eaglefront/node_modules/gulp-rev-outdated/index.js:23:32)
  at DestroyableTransform.Transform._read (/Users/alexanderkozhevin/Documents/eaglefront/node_modules/readable-stream/lib/_stream_transform.js:159:10)
  at DestroyableTransform.Transform._write (/Users/alexanderkozhevin/Documents/eaglefront/node_modules/readable-stream/lib/_stream_transform.js:147:83)
  at doWrite (/Users/alexanderkozhevin/Documents/eaglefront/node_modules/readable-stream/lib/_stream_writable.js:338:64)
  at writeOrBuffer (/Users/alexanderkozhevin/Documents/eaglefront/node_modules/readable-stream/lib/_stream_writable.js:327:5)
  at DestroyableTransform.Writable.write (/Users/alexanderkozhevin/Documents/eaglefront/node_modules/readable-stream/lib/_stream_writable.js:264:11)
  at write (/Users/alexanderkozhevin/Documents/eaglefront/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
  at flow (/Users/alexanderkozhevin/Documents/eaglefront/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
  at DestroyableTransform.pipeOnReadable (/Users/alexanderkozhevin/Documents/eaglefront/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
  at emitNone (events.js:86:13)
  at DestroyableTransform.emit (events.js:185:7)
  at emitReadable_ (/Users/alexanderkozhevin/Documents/eaglefront/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:448:10)
  at emitReadable (/Users/alexanderkozhevin/Documents/eaglefront/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:444:5)
  at readableAddChunk (/Users/alexanderkozhevin/Documents/eaglefront/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:187:9)
```

**Comment by AlexanderKozhevin** [comment]
Sorry, looks like previous task in sequence haven't been completed.
I fixed it.
